### ISSUE TITLE
exports.Td specified without a `data` property or children, ignoring

### ISSUE THREAD

**Issue by alfredo-cp** [glittershark/reactable#159] opened 2015-07-09 16:45 UTC
I'm trying to pass a custom component (which returns a ```Td``` component) to a ```Tr``` component but it doesn't work. I think for now it expects all children should be a ```Td```

```javascript
var CPTable = Reactable.Table,
   CPTr = Reactable.Tr;

var CPTaskTable = React.createClass({
  render: function () {
    var tableDataComponents;

    tableDataComponents = this.props.data.map(function (item, i, arr) {
      return (
        <CPTr key={i}>
          <CPTableCell cellType="dueDate" column="Due Date" value={item.due_date} />
        </CPTr>
      );
    });

    return (
        <CPTable className="cp-table-component">
          {tableDataComponents}
        </CPTable>
      );
  }
});
```

**Comment by glittershark** [comment] 2015-07-09 16:52
Dupe of #156 (except this one's with `Td` rather than `Tr`)

**Closed by glittershark** 2015-07-09 16:52 UTC
