### ISSUE TITLE
.map() inside Td

### ISSUE THREAD

**Issue by foodgy** [glittershark/reactable#258] opened 2016-03-21 11:02 UTC
Map inside Td always returns `[object Object]`.
Console log shows correct data.

```
<Table>
    <Tr>
        <Td column="Column">
        {data.map((item, i) => {
            console.log(item.name)
            return <span key={i}>{item.name}</span>
         })
         </Td>
    </Tr>
</Table>
```

This works fine

```
<Table>
    <Tr>
        <Td column="Column">
        {data.map((item, i) => {
            console.log(item.name)
            return item.name
         })
         </Td>
    </Tr>
</Table>
```

Why so?

**Comment by lgraubner** [comment] 2016-04-12 09:04
Use `unsafe()` to render your generated HTML.

**Comment by Circuit8** [comment] 2016-11-03 13:52
This has a solution in #240

**Comment by paddotk** [comment] 2016-11-11 09:59
@Circuit8 Doesn't look like it

**Comment by glittershark** [comment] 2016-11-18 21:18
Yeah, looks like a dupe of #240.

**Closed by glittershark** 2016-11-18 21:18 UTC
