### ISSUE TITLE
HTML in columns breaks filter?

### ISSUE THREAD

**Issue by MikaelLarsson** [glittershark/reactable#164] opened 2015-07-17 09:25 UTC
Trying to add some JSX in the one of the columns like:
```javascript
<Table data={{ Company: <Link to="editCustomer" params={{ customerId: customer.id }}> { customer.company }</Link> }} filterable={[ 'company' ]}
```

But makes the filter function unusable for the Company column. Is there a way around this currently?

**Comment by glittershark** [comment] 2015-07-17 13:27
Dupe of #162

**Closed by glittershark** 2015-07-17 13:27 UTC
