### ISSUE TITLE
Using elements inside custom table body with columns.map returns [object, Object]

### ISSUE THREAD

**Issue by JonathanBruce** [glittershark/reactable#226] opened 2015-12-15 16:08 UTC
So I'm using a custom body because I have to add some pseudo columns and additional content to table cells and I'm making the main content of the table via a columns.map return seen here.

```
{
    this.props.data.map((item, k) => {
        return (
            <Tr key={ k }>
                {
                    this.props.columns.map((col, kTwo) => {
                        return (
                            <Td className={ col === this.props.sortColumn ? 'sorting' : null } column={ col } key={ kTwo }>
                                { item[ col ] }
                                <Icons.ViewCampaign className='transition'/>
                            </Td>
                        );
                       })
                    }
                <Td column=' '>
                    <Icons.ViewCampaign className='transition'/>
                </Td>
            </Tr>
        );
    })
}
```

This returns 
<img width="194" alt="screen shot 2015-12-15 at 11 07 56 am" src="https://cloud.githubusercontent.com/assets/1743411/11815950/2883bc64-a31c-11e5-97e6-9966902ab324.png">
In the row, any idea why this might be happening?

**Comment by glittershark** [comment] 2015-12-15 16:16
Definitely sounds like a bug. Failing test case would be hugely appreciated, but not at all necessary.

**Comment by JonathanBruce** [comment] 2015-12-15 16:18
I can try to hook it up and check it out shortly, currently attempting to figure out a work around.

**Comment by Circuit8** [comment] 2016-11-03 13:52
This has workaround in #240

**Comment by glittershark** [comment] 2016-11-18 21:18
dupe of #240

**Closed by glittershark** 2016-11-18 21:18 UTC
Labels: Bug
