### ISSUE TITLE
When sorted column moves? (with gif)

### ISSUE THREAD

**Issue by reggi** [glittershark/reactable#192] opened 2015-09-21 06:26 UTC
![oldfashionedwildadder](https://cloud.githubusercontent.com/assets/296798/9986233/1d61c0bc-6008-11e5-9fdb-3cffc0566c70.gif)

What's happening here?

```jsx
var React = require('react')
var Reactable = require('reactable')
var Table = Reactable.Table

var data = [
  { Name: 'Griffin Smith', Age: 18 },
  { Age: 23, Name: 'Lee Salminen' },
  { Age: 28, Position: 'Developer' }
]

module.exports = React.createClass({
  displayName: 'Test',
  render: function () {
    return (
      <div>
        <Table className='table' data={data} sortable={['Name']}/>
      </div>
    )
  }
})
```

**Comment by glittershark** [comment] 2015-10-18 16:56
Dupe of #145

**Closed by glittershark** 2015-10-18 16:56 UTC
